name: Deploy to Laravel Server

on:
  push:
    branches:
      - main  # หรือ branch ที่ต้องการ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/lkungnb786.csbootstrap.com/laravel-Lnwza007
          git pull origin main
          composer install --no-interaction
          npm install
          npm run build
          php artisan migrate
          
# end
